baseURL = 'https://jbirnick.github.io/'
languageCode = 'en-us'
title = 'Personal Website of Johann&nbsp;Birnick'
theme = 'mathematician'
copyright = 'Copyright Â© 2022-{year} Johann Birnick'
disableKinds = ['taxonomy', 'term', 'sitemap', 'RSS']

[params]
author = 'Johann Birnick'

[frontmatter]
lastmod = ['lastmod']

[markup.goldmark.extensions]
linkify = false
